# Generated by Django 3.2.6 on 2021-09-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_the_bill', '0005_fund_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-create_time']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_deposit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_expense',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_withdrawal',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('user_to_user', 'User To User'), ('user_to_fund', 'User To Fund'), ('fund_to_user', 'Fund To User'), ('user_expense', 'User Expense'), ('fund_expense', 'Fund Expense')], default='user_to_user', max_length=12),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
    ]
