# Generated by Django 3.2.6 on 2021-09-02 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_the_bill', '0006_auto_20210902_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
