# Generated by Django 3.2.6 on 2021-09-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split_the_bill', '0009_alter_eventinvitation_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='invitations',
            new_name='invited_users',
        ),
    ]
