# Generated by Django 3.2.6 on 2021-09-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_the_bill', '0010_rename_invitations_event_invited_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='join_token',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='qr_code',
            field=models.ImageField(default='', upload_to='split_the_bill/event/qr_code/%Y/%m'),
            preserve_default=False,
        ),
    ]
