# Generated by Django 3.2.7 on 2021-10-08 15:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('split_the_bill', '0011_auto_20210916_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='split_the_bill.event')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_to_pay', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_to_receive', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event', 'amount'],
            },
        ),
    ]
