# Generated by Django 3.2.6 on 2021-09-03 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users/avatar/%Y/%m', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
