# Generated by Django 3.2.6 on 2021-09-06 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_thumbnail',
            field=models.ImageField(blank=True, upload_to='users/avatar_thumbnail/%Y/%m', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
