# Generated by Django 3.2.6 on 2021-09-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_avatar_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_avatar_url',
            field=models.URLField(blank=True),
        ),
    ]
