# Generated by Django 3.2.7 on 2021-09-23 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users/avatar/%Y/%m', validators=[django.core.validators.validate_image_file_extension], verbose_name='avatar'),
        ),
    ]
