# Generated by Django 3.2.7 on 2022-01-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookDataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('confirmation_code', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('fail', 'Fail')], default='pending', max_length=7)),
                ('issued_at', models.BigIntegerField()),
                ('expires', models.BigIntegerField()),
            ],
        ),
    ]
