# Generated by Django 3.2.7 on 2022-01-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20220103_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookdatadeletionrequest',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='facebookdatadeletionrequest',
            name='issued_at',
            field=models.DateTimeField(null=True),
        ),
    ]
